#!/usr/bin/env bash

script_dir=$(dirname "$(readlink -f "$0")")
check_link="$script_dir/check_link.py"

function interactive() {
  read -e -n 1 -p 'What would you like to add? ("n" for note, "e" to edit clipboard, "p" for clipboard content): ' userInput
  if [[ -z "$userInput" ]]; then
    exit 0
  else
    "$0" "$userInput"
    exit 0
  fi
}

case "$1" in
  "")
    interactive
    ;;
  "n")
    filename="$script_dir/note.md"
    nvim -c 'startinsert' $filename
    vim_pid=$!
    wait $vim_pid
    if [[ -f $filename ]]; then
      user_note=$(cat $filename)
      rm -f $filename
    else
      echo "Note not saved! Changes discarded."
      exit 0
    fi
    if [[ -z $user_note ]]; then
        echo "Your note is empty."
        exit 0
    fi
    hoarder bookmarks add --note "$user_note" > /dev/null
    ;;
  # "l")
  #   read -p "Enter your link: " user_link
  #   if [[ -z $user_link ]] || ! echo "$user_link" | $check_link; then
  #       echo "Wrong link format."
  #       exit 0
  #   fi
  #   hoarder bookmarks add --link "$user_link" > /dev/null
  #   ;;
  "e")
    filename="$script_dir/note.md"
    nvim -c "r!pbpaste" $filename
    vim_pid=$!
    wait $vim_pid
    if [[ -f $filename ]]; then
      user_note=$(cat $filename)
      rm -f $filename
    else
      echo "Note not saved! Changes discarded."
      exit 0
    fi
    if [[ -z $user_note ]]; then
        echo "Your note is empty."
        exit 0
    fi
    if echo "$user_note" | $check_link; then
        hoarder bookmarks add --link "$user_note" > /dev/null
    else
        echo "$user_note" | hoarder bookmarks add --stdin > /dev/null
    fi
    ;;
  "p")
    clipboard_contents=$(pbpaste)
    if [[ -z $clipboard_contents ]]; then
        echo "Your clipboard is empty."
        exit 0
    fi
    if echo "$clipboard_contents" | $check_link; then
        hoarder bookmarks add --link "$clipboard_contents" > /dev/null
    else
        echo "$clipboard_contents" | hoarder bookmarks add --stdin > /dev/null
    fi
    ;;
  *)
    exit 0
    ;;
esac
